language: c++

os:
  - linux
  
dist: bionic

sudo: enabled

compiler:
  - g++
  - clang++

branches:
  development

# commands that need to be run before installing the dependencies
# before_install:

# install all dependencies 
install: 
  - sudo apt update && sudo apt-get install -y clang-5.0 libclang-5.0-dev llvm-5.0 libboost-all-dev sqlite3 libsqlite3-dev bear python3 git cmake zlib1g-dev libncurses5-dev graphviz doxygen libcurl4-gnutls-dev libboost-dev libboost-dev libmysqlcppconn-dev
  - export PATH="/usr/lib/llvm-5.0/bin:$PATH"
  - git submodule update --init --recursive

# commands that need to be run before execution
# before_script

# build all interesting targets
script: 
  - mkdir -p build
  - cd build
  - echo "checking RAM"
  - cat /proc/meminfo
  - echo "checking CPU(s)"
  - cat /proc/cpuinfo
  - cmake -G "Unix Makefiles" -DBUILD_SHARED_LIBS=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPHASAR_BUILD_UNITTESTS=ON -DPHASAR_BUILD_DOC=ON ..
  - make -j4
# Fix the unit tests first 
#  - make test
