language: c++

addons:
  apt:
    sources:
      # - ubuntu-toolchain-r-test
    packages:
      - clang-5.0
      - libclang-5.0-dev
      - llvm-5.0
      - llvm-5.0-dev
      - sqlite3 
      - libsqlite3-dev 
      - bear 
      - python3 
      - git 
      - cmake 
      - zlib1g-dev 
      - libncurses5-dev 
      - graphviz 
      - doxygen 
      - libcurl4-gnutls-dev
      - libmysqlcppconn-dev

matrix:
  include:
  - os: linux
    dist: xenial
    sudo: enabled
    compiler:
      - clang++
  - os: osx
    osx_image: xcode8

branches:
  - development

# commands that need to be run before installing the dependencies
# before_install:

# install all dependencies 
install: 
  - export PATH="/usr/lib/llvm-5.0/bin:$PATH"
  - git submodule update --init --recursive
  # Install boost 1.67
  - wget https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.gz
  - tar xf boost_1_67_0.tar.gz
  - cd boost_1_67_0/
  - ./bootstrap.sh 1> /dev/null
  - sudo ./b2 -j2 install 1> /dev/null
  - cd ..

# commands that need to be run before execution
# before_script

# build all interesting targets
script: 
  - mkdir -p build
  - cd build
  - echo "checking RAM"
  - cat /proc/meminfo
  - echo "checking CPU(s)"
  - cat /proc/cpuinfo
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPHASAR_BUILD_UNITTESTS=ON ..
  - make -j2
# Fix the unit tests first 
#  - make test
